name: Deploy React site with secret API key

on:
  push:
    branches: [ main ]   # change to [ master ] if your default branch is master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v4

      # 2. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build React app
      - name: Build React app
        run: npm run build

      # 5. Replace API key in built JS
      - name: Replace API key in build folder
        run: |
          find build/static/js -type f -name "*.js" -print0 | \
          xargs -0 perl -pi -e 's|process\.env\.GEMINI_API|"${{ secrets.GEMINI_API }}"|g'

      # 6. Upload artifact for Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
