name: Deploy static site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Replace API key
        run: |
          sed -i "s|process.env.GEMINI_API|\"${{ secrets.GEMINI_API }}\"|g" index.html
          sed -i "s|process.env.GEMINI_API|\"${{ secrets.GEMINI_API }}\"|g" script.js
      
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v2

