name: Deploy static site with secret

on:
  push:
    branches: [ main ]   # or [ master ] if your repo uses master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace API key in HTML and JS
        run: |
          find . -type f \( -name "*.html" -o -name "*.js" \) -print0 | \
          xargs -0 perl -pi -e 's|process\.env\.GEMINI_API|"${{ secrets.GEMINI_API }}"|g'

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages   # ✅ required for Pages deployments
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
