name: Deploy React site with secret API key

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: List files in build folder
        run: find build

      - name: Replace API key in build folder
        run: |
          echo "Replacing API key in built JS files..."
          if [ -d "build" ]; then
            find build -type f -name "*.js" | while read file; do
              echo "Processing $file"
              sed -i "s|process\.env\.GEMINI_API|${GEMINI_API}|g" "$file"
            done
          else
            echo "Build folder not found! Exiting."
            exit 1
          fi
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
