name: Deploy static site with secret

on:
  push:
    branches: [ main ]   # or change to [ master ] if that's your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace API key in HTML and JS
        run: |
          find . -type f \( -name "*.html" -o -name "*.js" \) -print0 | \
          xargs -0 perl -pi -e 's|process\.env\.GEMINI_API|"${{ secrets.GEMINI_API }}"|g'

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
